export {default as Hero} from './Hero'
export {default as Header} from './Header'
export {default as About} from './About'
export {default as Banner} from './Banner'
export {default as Footer} from './Footer'
export {default as Values} from './Values'
export {default as Offers} from './Offers'